### ISSUE TITLE
Métricas indisponíveis não podem ter o valor 0

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/salic-ml-web#35]
Se os dados para uma métrica não estão disponíveis, não podemos informar que o valor é zero porque isto está errado. Substituir o valor por um traço. 

Exemplo: 

> **Novos fornecedores: -**
> *Não disponível*

**Comment by LucianoPC** [comment]
Já foi implementado pelo Eduardo, ficou como está na imagem abaixo, estou esperando validar para fechar a issue.

![image](https://user-images.githubusercontent.com/3257415/45383670-46364c00-b5e2-11e8-8ced-5b75d777b052.png)

**Comment by LucianoPC** [comment]
O Eduardo vai remover essas setinhas da direita de expandir o item quando ele não está disponível
