### ISSUE TITLE
Adicionar tratamento da aplicação em relação aos itens existentes

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/salic-ml-web#39]
- [ ] Booleano se tem item ou nao

- [ ] Hover informando por que nao tem 

Issue movida de https://github.com/lappis-unb/salic-ml/issues/144

**Comment by LucianoPC** [comment]
Conversei com o Maia e ficou no modelo abaixo, vou validar com a Carla usando e em seguida mando pra homologação e fecho essa issue.

![image](https://user-images.githubusercontent.com/3257415/45382278-1a18cc00-b5de-11e8-96d9-b7fff8b29d4f.png)
